# Generated by Django 3.1.3 on 2021-01-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='G_neighbour.location_model')),
            ],
        ),
    ]
