# Generated by Django 3.1.3 on 2020-11-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_card',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
