# Generated by Django 3.1.3 on 2021-01-04 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('G_neighbour', '0002_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_description',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
