# Generated by Django 3.1.3 on 2021-01-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0004_auto_20210105_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_description',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profiles'),
        ),
    ]
