# Generated by Django 3.1.3 on 2020-11-30 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('G_neighbour', '0004_auto_20201130_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donator',
        ),
        migrations.AlterField(
            model_name='donation_card',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='donation_card',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
