# Generated by Django 3.1.3 on 2021-01-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0005_profile_description_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_description',
            name='profile_pic',
        ),
    ]
