# Generated by Django 3.1.3 on 2020-12-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0006_request_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='information_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
