# Generated by Django 3.1.3 on 2020-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0007_information_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('number', models.IntegerField(blank=True)),
            ],
        ),
    ]
