# Generated by Django 3.1.3 on 2021-01-06 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('G_neighbour', '0007_rating_page_user_comment_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
