# Generated by Django 3.1.3 on 2020-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0008_emergency_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_page',
            name='number',
            field=models.CharField(max_length=150),
        ),
    ]
