# Generated by Django 3.1.3 on 2021-01-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_neighbour', '0012_private_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_message',
            name='title',
            field=models.CharField(default='new message', max_length=150),
        ),
    ]
